language: node_js
node_js:
- '7'
branches:
  only:
  - master
env:
  global:
    - secure: "PVayMWMhJPbf8BsPGBffJ4gZJvXt0t8BWTLbZPtFk6XhxTpVxZnKigEr7Pyyb2CkLFTNm2aUA0HhzsVXwYsJfqHCvkHu/6xf5LRf8n2DB+U/WOPODF9cKmtC/wMgiLGDMP/U9hXSxwuhhJ00VSbFPTtaOLb/QGcihWSSinbQ+OfQ2qMTw1sXKqOhuapUNfGv3VxeDmrEI1PVIIl6XQXRL5owQdCQdiUyPDmcU443N1jQQqKDAeVx4b2hjg4x0TxiDN3cbDUpt0BVodBOSakOOGqAwFWuzzhpGAxVN6re3cGgHn5TFj/PC5TGLZdXXFjG6TyBKMyj3l2vHi7oaEacgyp7fRn+RLGkNWwYD8FY8tkileps9t/0SJWph5Onk9AJJWb4BhjsS/le8TbUD1oaul5spPy0m1VZetp1n1uCOCl7HUFlXDoHIBhrNG9oGaInCYPbiSGvRF9KiJKqF5+lcOrtaAQGcn5YTefmXo2wYGHbyd4lIaCfYaBi/4GtnjSO6xy5jjzqh9J89NeK8xe6puyb6JCxl77xrNT2H/A+woJzNybAoOaBxUER5gK9mpBM/poorto8OXNWlZ4yRauQSn17+Pv51JjfuC6ci83N+v+0LBUG3NpicPXd+BZTV7dl8G0cMFH9lKdK0HyEFvat5yMKSn+5O5VGYcw0+yHeC/Q="
    - secure: "YYo9E9U+JGL2g0sSZ+HiAkdJPItf9kzR/gbunxrAwhdoRyNvvS2VYa7zubEV/ViPva5E9z4gqPk67kbd0EBh0AYtFbQDfdiNs9nuiZRA/c1UzsaCebqVaUY9af0wQ1qD0dH63r7mEz3xvU3k465vp4DQGIgwub+/seHjaxxTf8I1ntBvMHTo7U/DDEkP/ywxYeKoJd65IZOhCPj8Zv4RgIZV+eLmqNJxK1tV+jTbKHD3fOtik3aNaVHr0B/6pJiMQsOErLVYoSiYs9aTwcbvTJczAoITVIXXqooV1T89sQTqpjSPZpdvb7znckSzi2c8BK/6IM3jUxcZNd3tuv0GesktUkhJcu+KrDdsDClXaMyxYPHBcusi1MEoqSnfr+WsA2O/vs4VH6HTCKyOfldpzTmYNfwNMc0uh+o/jV1Z179LwUD4EYjSma8eeXEzxWkPju815lGUu2KPdisGc0WP9w5ggIh2KyXVaeDYQ3G+x3dIoxdDgKcsIOisM5+lmgvPUPQ8+skQg1Ok2DyNAypGomesK0cDKumm3KZ8Yul00PnVrXsUMTlpcSNu5M7iMplmfAoDezODlmwd06ncU47r4X0nQW4rDul9W4xlV1fHIQLm1+nrTAH0sqC3tmXlnjOpvyYWK/1mLyxj9/exMQPyl/sc6r9oV9MOga6qygJleLw="
    - secure: "SstLHvKywOJguEDGclm78WQrzWSVS+uROuNSrHJSXNt2agQSYECAPA7uYdONUwk3zYXyZS4bN4tyHnzi+mFdBtkY+gmhiXD4GTnOvv5ZU/PY4dDKRV/zd1fJcKKdDILrIKvSlTvsL7Qgs5QhTEb0w1/hj6lBoQ846JZNSzrARPMtQsmshFm3o799qU71drb0ZsJfZHGaIqOQeJRYjQzIg6XLVnND2X6cdk5LjvkhEKM0bUkxgTZcy8IqrBccr6LtsbnA/tFj19dilTPMy697gn+AiAvx99dUGt70VG9/+V4gg1NMiVO2k774Up9S1YqBzxY2B5EF8OauJYsIrT4FTfos+HTTxknaon+HiarnMtb4aJey9ElWnUhkFoKBr643CoppC8A2D/95Ozkyac4yv6GkowHyqAhXjoa6h4TS71nm2cSLXzpTMBbnfnSiyofuDaopHKdQw+JtDxlRbjuurogzAsYdfBrZ/6DP1uqLOgRvZMrLIJSCuTaOaa/riyJF+0dX1zO0EcCjDRzgf84b6YpGsM4Pn2hhviKkx3WLnyhSf2XEgTuYb0BmbDq8p65T6sRDa4sp2nZf6CNOyNCtHYx80T8vpBf/gfupNjbg+o8xgwC/5hpUdW669HoxMJMIO8x9aB8AcW/T/EnpP2eucrZH7wpB24yZ6SfIZGUa2Do="
    - secure: "PNlFLoR5hEbX0jRV6wuQNrykLCxprH48r3/haWSbpsmmHQ4Gga+kjdYhBfcPCm2AfXq1EHXR7F9V87pvUq4alf5tHigIkBf5/QAJJo79NrwHyckvY3BDE1vXTKibpDtVhI2XeLMMMHEVTjEwMRk+wlhtWhcHQO1BwvG2+Ew+n1MfMC5PBk0dtpMX+qU6nuM+zQq2al5ZBJSFgtrJEs4mH/w/O54QXb2349tmdcamaxZJVW7RCvzwZ4pFauPip9cVCPJ0IYirDCx4lK1X/EjC5Wqk8tv2AzriOoPWIgdhpjjosl9Sts33QQ5Vt2vVr2c0AYb3ejctkImYJ+ud/zdy6LGjnygwNuw1anGn+snoLgLOTsp4pV/keTiy5iJcSJPGqmlL7bUALSFqDHVBYk2DsaWGqprVJS2wLtFqx/7kXlRhgxrPdUkSaqgLkgdT//HNXNK0UWAcw9z6B14/dZSx+9Q7sEPvtxwRL/k+becjilFEiINOEO+uHb04Wp8/atwutUDduTPyPt9YFUVG2Zcg5DOPYrr0L1L2u2JOru1tDg4qRHqkf/kzSEzkz3z27DCZ1Lz6gsEpQ1EZo/X8BkcNKPwhIvL1CesUoz4g8yJnEh0jygZxdkMKEGYyzaIwE/9sbbBJF3u/FHuRezN+lBPuW2uVRdbLZfqfo43pcolrXH0="
addons:
  apt:
    packages:
      - sshpass
before_script:
  - npm install
script:
  - npm run webpack-prod
after_success:
  - mkdir archive
  - mv * archive
  - tar -czf package.tgz archive
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -p $DEPLOY_PASS scp package.tgz root@DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh

