language: node_js
node_js:
- '7'
branches:
  only:
  - master
env:
  global:
    - secure: "cJey9AtDUKTQXZdgN6HKe/9rt1yiT+QbnWZaoGxkyynAS0liv34BUQQQxfAo9pNfNaMLxHUo3CkrejmeyRbX2Ijy2uXn/iaTKwd2GWMiY0hc9ufqKAEiR1aASIQuq28HCNzCGrpBkW1u0Q+iOXgPUxus6Rr+/j0OzunLS11Xly0E9hYXBszhtdz7ex8T3/QHmiiHR0Ztx73xBU+x/jvmH2hBhOoBWQY0gFONGHYDTSmtrUVMaq5riG0PRkJieciKDbRrehRG9t9n9USFAt3PlbUHzMs4ry1HwQVtiisQrk0UgJ1ELf9yfoK0v5TaErTcjEsGhoPqEcQDDaNC5IWWkDCx3MttRWPQuyMlzTAlCbMZTuATIZumsKZaxLhLc1kDuRUoMV9p4yFY12V9RkV2amfr+qaktksKk7PqfJjztdWVB96WrvHAybY6bVXANE69XQ/FWU0Gq618uI3inES+IHNYS3RHVv3+DvIIlzhGhB2yXvZq4gBWXWFqi9XixVsgBamvl4TPYgX002UPnweZVyws06pwv7TDrDj7UgUrMRQJfpWZfCC0r5PqbvEca9s7bmsFwWb9FmHuw5IN9LNz4oonE1F6QxO0lVn8K5Pu3I3TZdAjwzmWNg3yY1pYS6vGAlPQxUGcSKvANPHO8Ycilx2PgOmg9zVDDdMHAiqywS4="
    - secure: "PXhC23VzNRF1kup0yxY/RCox/Y3YZlAAx2cE1q0e1gFhi2AME6lsKoEuEx9keVA4ODNME8nmj07Pfwa1UPQQi5Oqb6VLaqMQQsFCVuvzN9oZ3tcLaOKT+1RnHAPJS7LAV0KpMTXZtcERUxW+z33NihX2BFW3vu9K10oyKv2VKopijUPVKQUBy+zGmOIx1ETfreSpgaMob/wImPS6cKVYVEUSJsylk4DiXW7FUbH6yNJ7ZB5TE20ayd8BVMe3ckGrca/ePAAUhXCt9IDmdrxYBCk5DEK/vZ+0U8jqs4ViKdOpFSWGaO6PafOXpg+lQrWFx3dvUR5GQmpWSAv1IlwClKUP/V9Ij8DSohszXj1lj3QD9OFA3SqZNQnm06Nnd3UGORs2yOtwTvLIuEQMAHdUJL5I5nQO05nNNyAn7MHER7PLxVTsyPrcEIdvycqTIfES3e4NSx3lMOheLp7w4/dbQhDswNzVlkH7MjvojzfUGjeZOYlRf5Di+04ouXuWeAhjx09NRPLUiohAMJWoyEeDfsS4Xn7pRkwa8uNTE7vJLmpbamcpxSPYxUfaSrmJaAbE1yKW640KSIxUmkWXn5haz4VsOV7KyQGaQ94FSHBqTh82azLTy9EHNjYM9fmrbz/NOl0TGX8Uqb7i1D7Bv3WlQFB7OjBKIp5lIt79/uHlt6A="
    - secure: "Porsax6qmlWBjh5UTqAsMLWgKb6pwMooM4D+UoAld0ElZNAl9hlhcAbCEU78fX2+v5jqCKh9cR3qE9SyB4z4A5Q++3ePK0hAL5zGT77i38grk78cA6rbM+9UPo8m2hkB6EG8gYyhRNqM6Yj6Q0ODSzbu+CLUcO2rn1IRFA4EDumTk7YpoeyzVevjOQ3RKGbIRV4LCBVQbCsuIGGQ5/aoOurgGR/eZ4wp20c6NLPjnzSYsKXsFrY/N/9kHy8XmxM/1/8GGf15N5Dw7hRagqxD95BVzPqbIUS9YgiC+LLg+cEaBNFtEcVHwR64PNesbIcpL6XZNli68rXo9ovpNjDzYAx6okezNv6IvM4mlUDnUjZZ6qKrI5SlzkO82poH2UPVpGdVwKnBvqO3VV6uJ4X4toNpfU9VU7xSP83rQxQSqSz/+XOa+TO059LEie6D3pPN4oVH7bY3L4fwOyZoyyOe8FgNi7fHXqxr1OHf+UrP4ZfirxbSx2CG3PvVqycNAu1nydAivn2z+fTa5wwQvToKuxkFTw6Y47pJwkbPPnIimUFSOV+7ar79oStcTGqyTVv4x0i3UaWBXUcqWudZOPy5eSWBIAIBusnCIEbZQ6GILC1E6YrATYWxMDPcw6KzTKFE8CD3EbI2YVGZFPUSPjIlVCb18NUFTH8pXEb947vvOgY="
    - secure: "RIx3KhxrIkcVs8V+KkT5z5br0pKeuTrFSpG2DrND2sy/+V66LxGpXIpUaUxsEf+fTqpvzihcGMmieMu539/LdxYXNlFC226BkOzJq5Y1HXGMiI6CJOh19BjB+5YTYRNUhwWVMBI4UtrbLVGv7waO1NqRKr0AHpmhrmbWlKmfGHYhG5foeeSeGhD7Aab5kEUPaxECai2GB2StK4FOZMidoITYKBECZU4HCpZmgzn/7pFwmBkSL4dRy4IEk/mb7e5S45tx3yLo2jj47PkOkcFvj2Ysv+CEYsQScDMgYxcxAq1Lv8WjlA33yUUxDu9/rVwASGtIZA0t4UCIG2EC3TbL+IktVspj7BP3y95ChNs0tFthxkIBkQqsTlfXgXTJkbeZOYpMYP5omYYCeJNZPxVn8D89Xabji9bdtIUkDLqdYh5/lCUjh7Z9RgdiW6kQ8RsWmeNrLMIrl/W01uEt1fR9IDuvZESwbWZxGWRtiuVOK83rIchYEiHXPW9E4DFzICGcYD9VBgTwSF/eel5Jm7Jg4GtldFiMpcbL6gNX8pwJt/8YIUE9pJAiFxTX6ONJEXseWCCTRG2I1qaWM1+toRJve7oapJDdQ9kcPzsSZLdSOPOxqRz/xocFs/d9qM+Slw1yZLR53bdtj9ySoraCcBgHrRBtcAGwk4Zekrmn8hRqBA4="
addons:
  apt:
    packages:
      - sshpass
before_script:
  - npm install
script:
  - npm run webpack-prod
after_success:
  - mkdir archive
  - mv * archive
  - tar -czf package.tgz archive
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -p $DEPLOY_PASS scp package.tgz root@DEPLOY_HOST:$DEPLOY_PATH
  - sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST $DEPLOY_PATH/deploy.sh

